import NextUiProvider from "@/providers/NextUiProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import getCurrentUser from "@/lib/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  
  console.log(currentUser);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <NextTopLoader />
          <NextUiProvider>
            {children}
            {/* <AppProvider></AppProvider> */}
          </NextUiProvider>
      </body>
    </html>
  );
}
